name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # Future plans on ubuntu and macos, but currently not possible

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 2.1.x
      - name: Build with cake
        uses: cake-build/cake-action@v1.1.1
        with:
          script-path: setup.cake
          target: AppVeyor # This is just for testing
          verbosity: Diagnostic
          cake-version: 0.37.0
          cake-bootstrap: true
